variables:
  JALIEN_SETUP: 1
  JALIEN_SETUP_REPO: $CI_REPOSITORY_URL
  JALIEN_SETUP_BRANCH: $CI_COMMIT_REF_NAME

trigger_job:
  trigger:
    project: nhardi/jalien-ci
    branch: dev
    strategy: depend
