variables:
  JALIEN_SETUP: 1

trigger_job:
  trigger:
    project: nhardi/jalien-ci
    branch: test-replica
    strategy: depend
    variables:
      JALIEN_SETUP_REPO: $CI_REPOSITORY_URL
      JALIEN_SETUP_BRANCH: $CI_COMMIT_REF_NAME
