variables:
  JALIEN_SETUP: 1
  JALIEN_SETUP_REPO: https://gitlab.cern.ch/nhardi/jalien-setup.git
  JALIEN_SETUP_BRANCH: $CI_COMMIT_REF_NAME
  ROOT_DEBUG: 1

trigger_job:
  trigger:
    project: nhardi/jalien-ci
    branch: test-replica
    strategy: depend
