version: "3.9"
services:

  jcentral:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: gitlab-registry.cern.ch/jalien/jalien-setup/jalien-base:latest
    command: [ "/jalien-setup/bash-setup/entrypoint.sh" ]
    hostname: jcentral
    ports:
      - 8098:8098 # Java binary serialization
      - 8097:8097 # JSON WebSocket
      - 3307:3307 # MySQL
      - 8389:8389 # LDAP
    volumes:
      - $SHARED_VOLUME:/jalien-dev
      - $JALIEN_SETUP_DIR:/jalien-setup:ro
    environment:
      SE_HOST: se

  se:
    build:
      context: .
      dockerfile: Dockerfile.xrootd
    image: gitlab-registry.cern.ch/jalien/jalien-setup/xrootd-se:latest
    entrypoint: [ "bash" , "-c" ]
    command: [ "xrootd", "-c", "/etc/xrootd/xrootd-standalone.cfg" ]
    hostname: se
    ports:
      - 1094:1094 # XRootD
    volumes:
      - $SHARED_VOLUME:/jalien-dev
      - jsite-storage:/shared-volume

  ce:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: gitlab-registry.cern.ch/jalien/jalien-setup/jalien-base:latest
    command: bash /ce-setup/ce-entrypoint.sh
    hostname: "localhost.localdomain"
    environment:
      CONDOR_HOST: "schedd"
      USE_POOL_PASSWORD: "yes"
      LD_LIBRARY_PATH: "/tmp"
    volumes:
      - /cvmfs/alice.cern.ch:/cvmfs/alice.cern.ch
      - $SHARED_VOLUME:/jalien-dev
      - $JALIEN_SETUP_DIR/ce-setup:/ce-setup:ro
      - $JALIEN_SETUP_DIR/ce-setup/htcondor-conf/pool_password:/root/secrets/pool_password

  schedd:
    image: "htcondor/cm:8.9.6-el7"
    environment:
      USE_POOL_PASSWORD: "yes"
    volumes:
      - $JALIEN_SETUP_DIR/ce-setup/htcondor-conf/pool_password:/root/secrets/pool_password

  worker:
    image: "htcondor/execute:8.9.6-el7"
    command: [ "bash" , "/ce-setup/cvmfs-checker.sh" ]
    environment:
      CONDOR_HOST: "schedd"
      USE_POOL_PASSWORD: "yes"
    volumes:
      - /cvmfs/alice.cern.ch:/cvmfs/alice.cern.ch
      - $JALIEN_SETUP_DIR/ce-setup:/ce-setup:ro
      - $SHARED_VOLUME:/jalien-dev
      - $JALIEN_SETUP_DIR/ce-setup/htcondor-conf/pool_password:/root/secrets/pool_password

volumes:
  jsite-storage:
