version: "3.3"
services:
  JCentral-dev:
    image: jalien-base
    command: /jalien-setup/bash-setup/entrypoint.sh
    hostname: JCentral-dev
    ports:
      - 8098:8098 # Java binary serialization
      - 8097:8097 # JSON WebSocket
      - 3307:3307 # MySQL
      - 8389:8389 # LDAP
    volumes:
      - $SHARED_VOLUME:/jalien-dev
      - $JALIEN_SETUP_DIR:/jalien-setup:ro
    environment:
      SE_HOST: JCentral-dev-SE

  JCentral-dev-SE:
    image: xrootd-se
    entrypoint: bash -c
    command: xrootd -c /etc/xrootd/xrootd-standalone.cfg
    hostname: JCentral-dev-SE
    ports:
      - 1094:1094 # XRootD
    volumes:
      - $SHARED_VOLUME:/jalien-dev
      - jsite-storage:/shared-volume

  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: jalien-base
    entrypoint: /ce-setup/slurm-conf/docker-entrypoint.sh slurmdbd
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - $JALIEN_SETUP_DIR/ce-setup/slurm-conf/slurmdbd.conf:/etc/slurm/slurmdbd.conf
      - $JALIEN_SETUP_DIR/ce-setup/slurm-conf/slurm.conf:/etc/slurm/slurm.conf
      - $SHARED_VOLUME:/jalien-dev
      - $JALIEN_SETUP_DIR/ce-setup:/ce-setup:ro
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: jalien-base
    entrypoint: /ce-setup/slurm-conf/docker-entrypoint.sh slurmctld
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - $JALIEN_SETUP_DIR/ce-setup/slurm-conf/slurmdbd.conf:/etc/slurm/slurmdbd.conf
      - $JALIEN_SETUP_DIR/ce-setup/slurm-conf/slurm.conf:/etc/slurm/slurm.conf
      - /cvmfs/alice.cern.ch:/cvmfs/alice.cern.ch
      - $SHARED_VOLUME:/jalien-dev
      - $JALIEN_SETUP_DIR/ce-setup:/ce-setup:ro
      - slurm_jobdir:/data
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

  JCentral-dev-CE:
    image: jalien-base
    command: bash /ce-setup/ce-entrypoint.sh
    hostname: "localhost.localdomain"
    environment:
      LD_LIBRARY_PATH: "/tmp"
    depends_on:
      - mysql
    volumes:
      - $JALIEN_SETUP_DIR/ce-setup/slurm-conf/slurmdbd.conf:/etc/slurm/slurmdbd.conf
      - $JALIEN_SETUP_DIR/ce-setup/slurm-conf/slurm.conf:/etc/slurm/slurm.conf
      - /cvmfs/alice.cern.ch:/cvmfs/alice.cern.ch
      - $SHARED_VOLUME:/jalien-dev
      - $JALIEN_SETUP_DIR/ce-setup:/ce-setup:ro
      - slurm_jobdir:/data

  c1:
    image: jalien-base
    entrypoint: /ce-setup/slurm-conf/docker-entrypoint.sh slurmd
    hostname: c1
    container_name: c1
    volumes:
      - $JALIEN_SETUP_DIR/ce-setup/slurm-conf/slurmdbd.conf:/etc/slurm/slurmdbd.conf
      - $JALIEN_SETUP_DIR/ce-setup/slurm-conf/slurm.conf:/etc/slurm/slurm.conf
      - /cvmfs/alice.cern.ch:/cvmfs/alice.cern.ch
      - $JALIEN_SETUP_DIR/ce-setup:/ce-setup:ro
      - $SHARED_VOLUME:/jalien-dev
      - slurm_jobdir:/data
    expose:
      - "6818"
    depends_on:
      - "JCentral-dev-CE"
      
  c2:
    image: jalien-base
    entrypoint: /ce-setup/slurm-conf/docker-entrypoint.sh slurmd
    hostname: c2
    container_name: c2
    volumes:
      - $JALIEN_SETUP_DIR/ce-setup/slurm-conf/slurmdbd.conf:/etc/slurm/slurmdbd.conf
      - $JALIEN_SETUP_DIR/ce-setup/slurm-conf/slurm.conf:/etc/slurm/slurm.conf
      - /cvmfs/alice.cern.ch:/cvmfs/alice.cern.ch
      - $JALIEN_SETUP_DIR/ce-setup:/ce-setup:ro
      - $SHARED_VOLUME:/jalien-dev
      - slurm_jobdir:/data
    expose:
      - "6818"
    depends_on:
      - "JCentral-dev-CE"

volumes:
  jsite-storage:
  var_lib_mysql:
  slurm_jobdir: