version: "3.3"
services:
  JCentral-dev:
    image: jalien-base
    command: /jalien-setup/bash-setup/entrypoint.sh
    hostname: JCentral-dev
    ports:
      - 8098:8098 # Java binary serialization
      - 8097:8097 # JSON WebSocket
      - 3307:3307 # MySQL
      - 8389:8389 # LDAP
    volumes:
      - $SHARED_VOLUME:/jalien-dev
      - $JALIEN_SETUP_DIR:/jalien-setup:ro
    environment:
      SE_HOST: JCentral-dev-SE

  JCentral-dev-SE:
    image: xrootd-se
    entrypoint: bash -c
    command: xrootd -c /etc/xrootd/xrootd-standalone.cfg
    hostname: JCentral-dev-SE
    ports:
      - 1094:1094 # XRootD
    volumes:
      - $SHARED_VOLUME:/jalien-dev
      - jsite-storage:/shared-volume

  schedd:
    image: "htcondor/cm:8.9.6-el7"
    environment:
      USE_POOL_PASSWORD: "yes"
    volumes:
      - $JALIEN_SETUP_DIR/ce-setup/htcondor-conf/pool_password:/root/secrets/pool_password
      
  worker:
    image: "htcondor/execute:8.9.6-el7"
    command: bash /ce-setup/cvmfs-checker.sh
    environment:
      CONDOR_HOST: "schedd"
      USE_POOL_PASSWORD: "yes"
      NUM_CPUS: 8
    volumes:
      - /cvmfs/alice.cern.ch:/cvmfs/alice.cern.ch
      - $JALIEN_SETUP_DIR/ce-setup:/ce-setup:ro
      - $SHARED_VOLUME:/jalien-dev
      - $JALIEN_SETUP_DIR/ce-setup/htcondor-conf/pool_password:/root/secrets/pool_password
      - $JALIEN_SETUP_DIR/ce-setup/htcondor-conf/01-slotusers.conf:/etc/condor/config.d/01-slotusers.conf 

  JCentral-dev-CE:
    image: "jalien-base"
    command: bash /ce-setup/ce-entrypoint.sh first
    hostname: "localhost.localdomain"
    environment:
      CONDOR_HOST: "schedd"
      USE_POOL_PASSWORD: "yes"
      LD_LIBRARY_PATH: "/tmp"
    volumes:
      - /cvmfs/alice.cern.ch:/cvmfs/alice.cern.ch
      - $SHARED_VOLUME:/jalien-dev
      - $JALIEN_SETUP_DIR/ce-setup:/ce-setup:ro
      - $JALIEN_SETUP_DIR/ce-setup/htcondor-conf/pool_password:/root/secrets/pool_password
        
  JCentral-dev-CE-second:
    image: "jalien-base"
    command: bash /ce-setup/ce-entrypoint.sh second
    hostname: "localhost2.localdomain"
    environment:
      CONDOR_HOST: "schedd"
      USE_POOL_PASSWORD: "yes"
      LD_LIBRARY_PATH: "/tmp"
    volumes:
      - /cvmfs/alice.cern.ch:/cvmfs/alice.cern.ch
      - $SHARED_VOLUME:/jalien-dev
      - $JALIEN_SETUP_DIR/ce-setup:/ce-setup:ro
      - $JALIEN_SETUP_DIR/ce-setup/htcondor-conf/pool_password:/root/secrets/pool_password

volumes:
  jsite-storage:
  
