version: "3.3"
services:
  JCentral:
    image: jalien-dev
    command: /jalien-setup/bash-setup/entrypoint.sh
    ports:
      - 8098:8098
      - 8097:8097/tcp
      - 3307:3307
      - 8389:8389
    volumes:
      - $SHARED_VOLUME:/jalien-dev
      - $JALIEN_SETUP:/jalien-setup:ro
    environment:
      SE_HOST: JCentral-dev-SE

  JCentral-dev-SE:
    image: xrootd-se
    command: bash /runner.sh
    hostname: JCentral-dev-SE
    ports:
      - 1094:1094
    volumes:
      - $SHARED_VOLUME:/jalien-dev
      - jsite-storage:/shared-volume

volumes:
  jsite-storage:
