name: CI Check
on:
  pull_request:
    branches:
      - master

jobs:
  ci-cd-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Set up MySQL
      #   uses: mirromutth/mysql-action@v1.1
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      # - name: Build docker images
      #   run: |
      #     make all
      # - uses: actions/setup-java@v4
      #   with:
      #     distribution: "temurin" # See 'Supported distributions' for available options
      #     java-version: "21"

      - name: Run bash script
        run: |
          git clone https://github.com/FYP-Jalien/jalien.git
          cd bash
          # ./tasks/start.sh --shared
          cd ..
          cd test-suite
          ./index.sh
