name: CI Check
on:
  pull_request:
    branches:
      - master

jobs:
  ci-cd-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      # - name: Build docker images
      #   run: |
      #     make all
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "21"
      - name: Cloning Bash repository
        uses: actions/checkout@v2
        with:
          repository: FYP-Jalien/bash
          ref: main
      - name: List files
        run: |
          ls
      - name: Create config file
        run: |
          mv config.sh config/config.sh
      - name: Run bash script
        run: |
          ./tasks/start.sh --pre
